version: '3.9'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7471:7471"
    environment:
      - PORT=7471
      - FILE_PART=/app/instructions_file/instructions.txt
    command: [ /app/cmd/main ]