name: deploy-go

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Set up Go v 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: build and test
        run: make test

